### ISSUE TITLE
Fail gracefully when provisioning services

### ISSUE THREAD

**Issue by cshunger** [ibm-bluemix-mobile-services/bluemix-generator#33]
Right now if provisioning a service fails, which it does frequently, you should still continue provisioning the rest of the services. Then provide a list of which services failed to provision, and maybe a link to bluemix to provision those failed services manually.

**Comment by jmeis** [comment]
This would be nice in the future, but at this time, the services are too different to make this implementation straightforward. 

Additionally, the directions post-bluegen would be incorrect because we assume the application is tightly coupled to the Bluemix services. Doing a `cf push` or another command after bluegen has finished running would result in more errors.
